#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'qbittorrent'
        intport: '8080'
        extport: '8083'
        image: 'linuxserver/qbittorrent'

    # CORE (MANDATORY) #############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/plexguide/containers/_core.yml'

    # FOLDER CREATION #############################################################
    - name: 'Including folders'
      include_tasks: '/opt/plexguide/containers/_folders.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}},{{tldset}}'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - '/opt/appdata/{{pgrole}}:/config'
          - '{{path.stdout}}:{{path.stdout}}'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: 1000
          PGID: 1000

    # MAIN DEPLOYMENT #############################################################
    - name: 'Checking for existing app data'
      stat:
        path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
      register: confcheck

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'

    # CONFIGURATION ####################################################
    - name: 'Wating for {{pgrole}} to start'
      wait_for:
      path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
      state: present
      
    - name: 'Stopping {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        state: stopped

    - name: Set SavePath
      ini_file:
        path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
        section: Preferences
        option: Downloads\SavePath
        value: '{{path.stdout}}/downloads/{{pgrole}}'
        state: present

    - name: Set TempPath when incomplete is defined
      ini_file:
        path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
        section: Preferences
        option: Downloads\TempPath
        value: '{{incomplete.stdout}}/{{pgrole}}'
        state: present
      when: incomplete.stdout | length > 0

    - name: Set TempPath when incomplete is undefined
      ini_file:
        path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
        section: Preferences
        option: Downloads\TempPath
        value: '{{path.stdout}}/incomplete/{{pgrole}}'
        state: present
      when: incomplete.stdout | length == 0

    - name: Set TempPathEnabled when incomplete is undefined
      ini_file:
        path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
        section: Preferences
        option: Downloads\TempPathEnabled
        value: false
        state: present
      when: incomplete.stdout | length == 0


    # FIRST TIME CONFIGURATION ####################################################
    - name: 'Configuring {{pgrole}} for first time use'
      block:
        - name: Enable AutoRun
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: AutoRun
            option: enabled
            value: true
            state: present

        - name: Enable Auto UnRar
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: AutoRun
            option: program
            value: '/usr/bin/unrar x -r \"%F/.\" \"%F/\"'
            state: present

        - name: Disable DHT
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: Preferences
            option: Bittorrent\DHT
            value: false
            state: present

        - name: Disable PeX
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: Preferences
            option: Bittorrent\PeX
            value: false
            state: present

        - name: Disable LSD
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: Preferences
            option: Bittorrent\LSD
            value: false
            state: present

        - name: Enable Encryption
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: Preferences
            option: Bittorrent\Encryption
            value: 1
            state: present

        - name: Use incomplete extension
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: Preferences
            option: Downloads\UseIncompleteExtension
            value: false
            state: present

        - name: Ignore slow torrents
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: Preferences
            option: Queueing\IgnoreSlowTorrents
            value: true
            state: present

        - name: Set MaxActiveDownloads
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: Preferences
            option: Queueing\MaxActiveDownloads
            value: 10
            state: present

        - name: Set MaxActiveTorrents
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: Preferences
            option: Queueing\MaxActiveTorrents
            value: 100
            state: present

        - name: Set MaxActiveUploads
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: Preferences
            option: Queueing\MaxActiveUploads
            value: 100
            state: present

        - name: Set GlobalMaxSeedingMinutes
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: BitTorrent
            option: Session\GlobalMaxSeedingMinutes
            value: 20160
            state: present

        - name: Set MaxRatio
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: Preferences
            option: Bittorrent\MaxRatio
            value: 1
            state: present

        - name: pause on MaxRatioAction
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: Preferences
            option: Bittorrent\MaxRatioAction
            value: 1
            state: present

        - name: Set default user - plexguide
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: Preferences
            option: WebUI\Username
            value:
            allow_no_value: yes
            force: yes
            state: present
        
        - name: Disable csrf
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: Preferences
            option: WebUI\CSRFProtection
            value: false
            force: yes
            state: present

        - name: Set default pass - plexguide
          ini_file:
            path: '/opt/appdata/{{pgrole}}/qBittorrent/qBittorrent.conf'
            section: Preferences
            option: WebUI\Password_ha1
            value:
            allow_no_value: yes
            force: yes
            state: present

      #when: not confcheck.stat.exists

      
    - name: Restart {{pgrole}}
      docker_container:
        name: '{{pgrole}}'
        state: started
